//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int STAFF_ID { get; set; }
        public string STAFF_NAME { get; set; }
        public string STAFF_QUALIFICATION { get; set; }
        public Nullable<int> STAFF_AGE { get; set; }
        public string SPECIALIZATION { get; set; }
        public Nullable<int> SALARY { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public string LOCATION { get; set; }
    }
}
